name: build

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: print username
        run: echo ${{ inputs.username }}
