name: build and push

on:
  workflow_call:
    inputs:
      imagename:
        required: true
        type: string

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: print username
        run: echo ${{ secret.DOCKER_USERNAME }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

#      - name: Build and push
#        id: docker_build
#        uses: docker/build-push-action@v2
#        with:
#          context: images/${{ inputs.imagename }}
#          tags: quay.io/mdipietro_1/${{ inputs.imagename }}:${{ github.event.number }}

#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v1

      - name: Login to Quay.io
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: images/${{ inputs.imagename }}
          tags: quay.io/mdipietro_1/${{ inputs.imagename }}:${{ github.event.number }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

#      - uses: actions/checkout@v2
#      - name: print username
#        run: echo ${{ inputs.username }}
#      - name: print PR
#        run: echo ${{github.event.number}}
