name: build

on:
  pull_request:
    paths:
      - images/renderer/**


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: dipietrom/paws/.github/workflows/composite.yaml
        with:
          username: woo

#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v1
#
#      - name: Build and push
#        id: docker_build
#        uses: docker/build-push-action@v2
#        with:
#          context: images/renderer
#          tags: quay.io/mdipietro_1/renderer:githubaction
